name: AniFree
description: Anime Streaming App.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.8.1
  cupertino_icons: ^0.1.2
  carousel_slider: ^1.4.1
  http: ^0.12.0+4
  animated_text_kit: ^2.0.0
  modal_progress_hud: ^0.1.3
  video_player: ^0.10.8+1
  webview_flutter: ^0.3.19+9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  
  assets:
    - assets/

  fonts:
     - family: Roboto
       fonts:
         - asset: fonts/Roboto-Regular.ttf

     - family: OTR
       fonts:
         - asset: fonts/OvertheRainbow-Regular.ttf

     - family: PressStart2P
       fonts:
         - asset: fonts/PressStart2P-Regular.ttf

     - family: Montserrat
       fonts:
         - asset: fonts/Montserrat-Regular.ttf
         - asset: fonts/Montserrat-Italic.ttf
           style: italic
         - asset: fonts/Montserrat-Bold.ttf
           weight: 700
         - asset: fonts/Montserrat-Light.ttf
           weight: 100
