name: AniFree
description: Anime Streaming App.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.8.1
  cupertino_icons: ^0.1.2
  carousel_slider: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  
  assets:
    - assets/

  fonts:
     - family: Roboto
       fonts:
         - asset: fonts/Roboto-Regular.ttf
